In [2]:
import numpy as np
import networkx as nx
import time
import matplotlib.pyplot as plt
import scipy.sparse as sp
import scipy.sparse.csgraph as csgraph
from numpy  import *

# Calcula a matriz de menores distâncias D
def distance(G):
    N = len(G)
    D = np.zeros(shape=(N,N))
    
    for i in range(N):
        lengths = nx.shortest_path_length(G, source=i)
        for j in range(i+1, N):
            D[i][j] = lengths.get(j, 0)
            D[j][i] = D[i][j]
    
    np.fill_diagonal(D, 0)
    return D

G = nx.read_edgelist("data/advogato.txt")
G = G.to_undirected()
Gcc = sorted(nx.connected_components(G), key=len, reverse=True)
G = G.subgraph(Gcc[0])
G = nx.convert_node_labels_to_integers(G, first_label=0)
matrix = nx.adjacency_matrix(G).toarray()

D = distance(G)

A = nx.adjacency_matrix(G).toarray()
# Converta a matriz de adjacência em uma matriz esparsa
adj_sparse = sp.csr_matrix(A)

# Encontre a matriz de menores distâncias usando o algoritmo de Dijkstra
dist_matrix = csgraph.shortest_path(adj_sparse, method='D', directed=False)


print(D)
print(dist_matrix)

[[0. 1. 1. ... 4. 4. 2.]
 [1. 0. 1. ... 3. 4. 3.]
 [1. 1. 0. ... 4. 4. 3.]
 ...
 [4. 3. 4. ... 0. 4. 4.]
 [4. 4. 4. ... 4. 0. 4.]
 [2. 3. 3. ... 4. 4. 0.]]
  (0, 0)	1
  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (0, 4)	1
  (0, 5)	1
  (0, 6)	1
  (0, 7)	1
  (0, 8)	1
  (0, 150)	1
  (0, 629)	1
  (0, 645)	1
  (0, 745)	1
  (0, 1198)	1
  (0, 1481)	1
  (0, 2277)	1
  (0, 2278)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (1, 406)	1
  (1, 645)	1
  (1, 970)	1
  (1, 2277)	1
  (1, 3102)	1
  :	:
  (5030, 43)	1
  (5030, 364)	1
  (5030, 801)	1
  (5031, 32)	1
  (5031, 116)	1
  (5031, 555)	1
  (5032, 317)	1
  (5033, 386)	1
  (5034, 603)	1
  (5035, 593)	1
  (5036, 470)	1
  (5037, 158)	1
  (5037, 165)	1
  (5037, 216)	1
  (5037, 1073)	1
  (5037, 1112)	1
  (5037, 1467)	1
  (5037, 5038)	1
  (5038, 5037)	1
  (5039, 614)	1
  (5039, 5039)	1
  (5040, 1035)	1
  (5040, 5040)	1
  (5041, 160)	1
  (5041, 629)	1
