In [5]:
import time
import numpy as np
from numpy  import *
import networkx as nx
import scipy.sparse as sp
import scipy.sparse.csgraph as csgraph

# Calcula a matriz de menores distâncias D
def distance(G):
    N = len(G)
    D = np.zeros(shape=(N,N))
    
    for i in range(N):
        lengths = nx.shortest_path_length(G, source=i)
        for j in range(i+1, N):
            D[i][j] = lengths.get(j, 0)
            D[j][i] = D[i][j]
    
    np.fill_diagonal(D, 0)
    return D

G = nx.read_edgelist("data/advogato.txt")
G = G.to_undirected()
Gcc = sorted(nx.connected_components(G), key=len, reverse=True)
G = G.subgraph(Gcc[0])
G = nx.convert_node_labels_to_integers(G, first_label=0)
matrix = nx.adjacency_matrix(G).toarray()

start_time = time.time()
D = distance(G)
end_time = time.time()
time1 = end_time - start_time

start_time = time.time()
A = nx.adjacency_matrix(G).toarray()
end_time = time.time()
time2 = end_time - start_time

adj_sparse = sp.csr_matrix(A)
dist_matrix = csgraph.shortest_path(adj_sparse, method='D', directed=False)

print("result 1:")
print(D)
print("result 2;")
print(dist_matrix)
print("array equal: ", np.array_equal(D, dist_matrix))
print("time 1 = ", time1)
print("time 2 = ", time2)

result 1:
[[0. 1. 1. ... 4. 4. 2.]
 [1. 0. 1. ... 3. 4. 3.]
 [1. 1. 0. ... 4. 4. 3.]
 ...
 [4. 3. 4. ... 0. 4. 4.]
 [4. 4. 4. ... 4. 0. 4.]
 [2. 3. 3. ... 4. 4. 0.]]
result 2;
[[0. 1. 1. ... 4. 4. 2.]
 [1. 0. 1. ... 3. 4. 3.]
 [1. 1. 0. ... 4. 4. 3.]
 ...
 [4. 3. 4. ... 0. 4. 4.]
 [4. 4. 4. ... 4. 0. 4.]
 [2. 3. 3. ... 4. 4. 0.]]
array equal:  True
time 1 =  54.0637948513031
time 2 =  0.14721345901489258
